<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**\*_comentada.cs" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="Exists('$(SolutionDir)Debug\BillarLogica.dll')">
    <Exec Command="xcopy /Y &quot;$(SolutionDir)Debug\BillarLogica.dll&quot; &quot;$(TargetDir)&quot; /R" />
  </Target>

</Project>
